### ISSUE TITLE
investigate WiseView FITS cutout API for determining image stretch parameters

### ISSUE THREAD

**Issue by ameisner** [coolneighbors/flipbooks#10]
I think this belongs here in the `flipbooks` repo more so than in the `ZPipe` repo?

**Comment by ameisner** [comment]
Here's something I did that just downloaded a file called "cutout" :

http://byw.tools/cutout?ra=0&dec=0&size=60&band=2&epoch=0

Quite possibly this URL pattern is very outdated and/or non-optimal, but it's what I could dig up quickly in my e-mail.

**Comment by ameisner** [comment]
```
In [1]: import astropy.io.fits as fits

In [2]: hdul = fits.open('cutout')

In [3]: hdul.info()
Filename: cutout
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  coadded image, outliers removed    1 PrimaryHDU      41   (61, 61)   float32  
```

**Comment by austinh2001** [comment]
Dan had said this would be too expensive, so I will investigate doing this by directly requesting unWISE
